### SmartCart Customer Clustering

In [4]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv("smartcart_customers.csv")

In [7]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Complain,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,172,88,88,3,8,10,4,7,0,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,2,1,6,2,1,1,2,5,0,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,111,21,42,1,8,2,10,4,0,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,10,3,5,2,2,0,4,6,0,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,46,27,15,5,5,3,6,5,0,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  Complain             2240 non-null   int64
 21  Response             2240 non-null   int64
dtypes: float64(1), int64(18), object(3)
memory usage: 385.1+ KB

In [9]:
df.shape

(2240, 22)

In [10]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
Complain                0
Response                0
dtype: int64

### Data Preprocessing

In [11]:
#lowercasing all attributes values of dataset

df.columns = df.columns.str.lower()

In [22]:
# replacing null value in income with its median

df['income'] = df['income'].fillna(df['income'].median())

In [23]:
df.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
complain               0
response               0
dtype: int64

### Feature engineering

In [24]:
df.columns

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'complain', 'response'],
      dtype='object')

In [36]:
#Customer tenure Feature

df['dt_customer'] = pd.to_datetime(df['dt_customer'],dayfirst=True)

df['cutomer_tenure'] = df['dt_customer'].max() - df['dt_customer']

In [38]:
#age columns from year of birth

df['age'] = 2026 - df['year_birth']

In [40]:
#total spending 

df['total_spending'] = df['mntwines'] + df['mntfruits'] + df['mntmeatproducts'] + df['mntfishproducts'] + df['mntsweetproducts'] + df['mntgoldprods']

In [42]:
df['education'].value_counts()

education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [ ]:
#education 

df['education'] = df['education'].replace({
    "Graduation":"Graduate",
    "2n Cycle":"UnderGraduate",
    "Basic":"UnderGraduate",
    "Master":"PostGraduate",
    "PhD":"PostGraduate",
})

In [47]:
df['education'].value_counts()

education
Graduate         1127
PostGraduate      856
UnderGraduate     257
Name: count, dtype: int64

In [49]:
df['marital_status'].value_counts()

marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [51]:
#maritial staus -> Living alone

single_status_cols = ['YOLO','Absurd', 'Alone','Widow','Divorced','Single']

df ['living_alone'] = df['marital_status'] == single_status_cols

ValueError: ('Lengths must match to compare', (2240,), (6,))

In [44]:
df.head()

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numdealspurchases,numwebpurchases,numcatalogpurchases,numstorepurchases,numwebvisitsmonth,complain,response,cutomer_tenure,age,total_spending
0,5524,1957,Graduate,Single,58138.0,0,0,2012-09-04,58,635,...,3,8,10,4,7,0,1,663 days,69,1617
1,2174,1954,Graduate,Single,46344.0,1,1,2014-03-08,38,11,...,2,1,1,2,5,0,0,113 days,72,27
2,4141,1965,Graduate,Together,71613.0,0,0,2013-08-21,26,426,...,1,8,2,10,4,0,0,312 days,61,776
3,6182,1984,Graduate,Together,26646.0,1,0,2014-02-10,26,11,...,2,2,0,4,6,0,0,139 days,42,53
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,5,3,6,5,0,0,161 days,45,422

#### visulising the data

In [ ]:
#pairplot

cols=['']

### Data Visualisation

In [ ]:
## creating a paiplot

cols=[]

sns.pairplot()